import coreWebVitals from 'eslint-config-next/core-web-vitals'
import typescript from 'eslint-config-next/typescript'

const config = [
  ...coreWebVitals,
  ...typescript,
  {
    // Generated by the Payload CLI — regenerated on demand, never hand-edited.
    ignores: [
      'src/payload-types.ts',
      'src/app/(payload)/**',
      '.next/**',
      'scripts/legacy/**',
    ],
  },
]

export default config
