/**
 * Turns the portrait photo into a character map, once, at authoring time.
 *
 * This runs on a machine, not in a browser: the site ships a compact string and
 * never decodes a 2.8MB PNG to build the portrait. The static render is real text
 * in the HTML, so it is visible on first paint with no JavaScript and is also the
 * reduced-motion version.
 *
 * Usage: npx tsx scripts/generate-ascii.ts [source] [columns]
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import sharp from 'sharp'

const SOURCE = process.argv[2] ?? 'public/images/professional_picture.png'
const COLUMNS = Number(process.argv[3] ?? 78)
const OUT = 'src/components/ascii-portrait/portrait-data.ts'

/**
 * Darkest to lightest. Chosen for even perceived-weight steps in JetBrains Mono
 * rather than for looking like code: an uneven ramp reads as noise, not as a face.
 */
const RAMP = '@%#*+=-:'

/**
 * Must match the component's rendering exactly or the portrait comes out
 * squashed. JetBrains Mono advances 0.6em per character and the portrait is set
 * at 1.05 line-height, so one cell is 0.6 wide by 1.05 tall.
 */
const CHAR_ADVANCE = 0.6
const LINE_HEIGHT = 1.05
const CELL_ASPECT = CHAR_ADVANCE / LINE_HEIGHT

const main = async () => {
  const image = sharp(SOURCE)
  const meta = await image.metadata()
  if (!meta.width || !meta.height) throw new Error(`Cannot read dimensions of ${SOURCE}`)

  const rows = Math.round((COLUMNS * (meta.height / meta.width)) * CELL_ASPECT)

  /**
   * The source is a cutout with a transparent background, and the subject wears
   * black. Luminance alone cannot tell the two apart: both are 0, so the sweater
   * disappears and the portrait becomes a floating head.
   *
   * Alpha decides what is subject and what is background; luminance only decides
   * which character to use inside the subject. The darkest part of the subject
   * still gets the lightest visible glyph rather than a space, so the silhouette
   * survives.
   */
  const { data } = await image
    .trim({ threshold: 12 })
    .resize(COLUMNS, rows, { fit: 'fill' })
    // Pull the subject's own tonal range apart. Without this the black sweater
    // and the shadowed side of the face land on the same glyph and the portrait
    // flattens into a silhouette.
    .modulate({ brightness: 1.18 })
    .linear(1.35, -22)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })

  const ALPHA_THRESHOLD = 96
  // The ramp holds ink only. Background is a space, decided by alpha, never by
  // luminance: '.' and ' ' as the darkest steps left the silhouette so sparse it
  // read as noise instead of a body.
  const maxInk = RAMP.length - 1

  const lines: string[] = []
  for (let y = 0; y < rows; y++) {
    let line = ''
    for (let x = 0; x < COLUMNS; x++) {
      const offset = (y * COLUMNS + x) * 4
      const alpha = data[offset + 3] ?? 0

      if (alpha < ALPHA_THRESHOLD) {
        line += ' '
        continue
      }

      const r = data[offset] ?? 0
      const g = data[offset + 1] ?? 0
      const b = data[offset + 2] ?? 0
      const luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b

      // Inverted: the page is dark and the glyphs are light, so a bright pixel
      // needs the densest character.
      const index = Math.min(maxInk, Math.round((1 - luminance / 255) * maxInk))
      line += RAMP[index]
    }
    lines.push(line)
  }

  const file = `/* GENERATED by scripts/generate-ascii.ts — do not edit by hand. */
/* Source: ${SOURCE} */

export const PORTRAIT_COLUMNS = ${COLUMNS}
export const PORTRAIT_ROWS = ${rows}

export const PORTRAIT_ROWS_DATA: readonly string[] = [
${lines.map((line) => `  ${JSON.stringify(line)},`).join('\n')}
]

export const PORTRAIT_TEXT = PORTRAIT_ROWS_DATA.join('\\n')
`

  await mkdir(path.dirname(OUT), { recursive: true })
  await writeFile(OUT, file, 'utf8')

  const bytes = Buffer.byteLength(file, 'utf8')
  console.log(`${COLUMNS}x${rows} characters written to ${OUT} (${(bytes / 1024).toFixed(1)}KB)`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
